/**
 * ずかん（100種）のデータ。サーバー（gas/Code.gs の ZUKAN_POOL）と同じ id・同じ順番。
 * 並べかえ・id の変更はしない（あとから足すときは最後に追加し、Code.gs の ZUKAN_POOL にも足す）。
 *
 * 1種ごと：{ id, tier(1〜3＝レア★1〜★3, 4＝SR), emoji, name, illust, photo, tips }
 *   illust … レベル2のイラスト。Microsoft Fluent Emoji 3D（MIT ライセンス）のフォルダ名。
 *            "/" を含むときはフォルダからのパス。{wiki: [ファイル名, ライセンス, 作者]} なら Wikimedia Commons の画像
 *   photo  … レベル3の写真。Wikimedia Commons の [ファイル名, ライセンス, 作者]（画面にクレジットを出す）
 *   tips   … 豆知識 [小学生レベル（レベル1）, 大人レベル（レベル2）, 専門家レベル（レベル3）]
 *
 * レベル：同じものを集めた数で上がる（levels の [レベル2に必要な数, レベル3に必要な数]。レアのランクごと）
 *   レベル1＝絵文字、レベル2＝イラスト、レベル3＝写真。レベルが上がるごとに豆知識が1つずつ読めるようになる
 */
window.OKD_ZUKAN = {
  levels: { 1: [3, 10], 2: [3, 8], 3: [2, 5], 4: [2, 5] },
  fluentBase: 'https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@1ffb34c752ecf5d402f04cfb4b392c77f57c54bc/assets/',
  items: [
    // ---------- レア★1 ----------
    { id: 'star', tier: 1, emoji: '⭐', name: 'ほし', illust: 'Star',
      photo: ['Pleiades large.jpg', 'Public domain', 'NASA, ESA, AURA/Caltech, Palomar Observatory'],
      tips: ['夜空の星の光は、何年も前に星を出発した光。いま見ているのは星の「むかしの写真」みたいなものなんだって。',
        '夜空でいちばん明るい恒星はシリウス。太陽系の近くにある恒星のひとつで、約8.6光年はなれている。',
        '恒星の色は表面の温度をあらわす。赤い星は約3000度、青白い星は1万度をこえる。太陽は約5800度の黄色い星。'] },
    { id: 'pig', tier: 1, emoji: '🐷', name: 'ぶた', illust: 'Pig face',
      photo: ['Pig farm Vampula 1.jpg', 'CC BY-SA 4.0', 'kallerna'],
      tips: ['ぶたはじつはきれい好き。トイレの場所をきめて、ねる場所とちゃんと分けるんだよ。',
        'ぶたは汗をかく汗腺がほとんどなく、汗で体を冷やせない。だから泥あびをして体温を下げる。泥は日やけや虫よけにもなる。',
        'ぶたの嗅覚はとても鋭く、ヨーロッパでは土の中のトリュフ（高級きのこ）さがしに使われてきた。いまは木を傷つけにくい犬が主流。'] },
    { id: 'cat', tier: 1, emoji: '🐱', name: 'ねこ', illust: 'Cat face',
      photo: ['Siam lilacpoint.jpg', 'CC BY-SA 3.0', 'Karin Langner-Bahmann'],
      tips: ['ねこは1日の半分以上ねている。「よく寝る子」で「ねこ」になった、という説もあるんだって。',
        'ねこは甘みを感じるしくみ（受容体）の遺伝子がはたらいておらず、甘さをほとんど感じないと考えられている。',
        'ねこのゴロゴロ音は約25〜150ヘルツの低い振動。この振動が骨の治りを助けるのでは、という研究上の仮説もある。'] },
    { id: 'dog', tier: 1, emoji: '🐶', name: 'いぬ', illust: 'Dog face',
      photo: ['Huskiesatrest.jpg', 'CC BY 2.0', 'M. Rehemtulla'],
      tips: ['いぬの鼻のもようは1ぴきずつちがう。人の指紋みたいに「鼻紋（びもん）」っていうんだよ。',
        'いぬの嗅覚は人の数千〜数万倍ともいわれ、においを感じる細胞は人の数十倍もある。',
        'いぬは人と暮らすうちに、でんぷんを分解する遺伝子（AMY2B）の数がふえた。人の食べ物に合わせて進化した証拠とされる。'] },
    { id: 'onigiri', tier: 1, emoji: '🍙', name: 'おにぎり', illust: 'Rice ball',
      photo: ['小料理バルさくら 特製おにぎり.jpg', 'CC BY-SA 4.0', '脇山航'],
      tips: ['おにぎりの形は三角だけじゃない。地方によっては、まるや俵（たわら）の形が人気なんだって。',
        '石川県の弥生時代の遺跡からは、炭になった米のかたまり「日本最古のおにぎりの化石」が見つかっている。',
        '冷めたご飯は、でんぷんの一部が消化されにくい「レジスタントスターチ」に変わる。冷めたおにぎりは血糖値が上がりにくいといわれる。'] },
    { id: 'apple', tier: 1, emoji: '🍎', name: 'りんご', illust: 'Red apple',
      photo: ['Apfel-Fuji.jpg', 'CC BY-SA 4.0', 'Superbass'],
      tips: ['りんごは水にうくよ。中に空気がたくさんつまっているからなんだ。お風呂でためしてみて！',
        'りんごの品種は世界に数千以上。「ふじ」は日本生まれで、世界でいちばん多く作られている品種のひとつ。',
        'りんごは種から育てると親とちがう性質になるので、同じ品種は「接ぎ木」でふやす。どの「ふじ」も最初の1本のクローンといえる。'] },
    { id: 'banana', tier: 1, emoji: '🍌', name: 'バナナ', illust: 'Banana',
      photo: ['Bananavarieties.jpg', 'CC BY-SA 3.0', 'TimothyPilgrim'],
      tips: ['バナナは木じゃなくて、じつは大きな大きな「草」のなかまなんだって！',
        '植物学では、バナナは「ベリー」のなかまに分けられる。反対に、いちごは植物学ではベリーではない。',
        '輸出用のバナナの多くは「キャベンディッシュ」という品種で、遺伝的にほぼ同じクローン。そのため病気（新パナマ病）に弱いことが問題になっている。'] },
    { id: 'frog', tier: 1, emoji: '🐸', name: 'かえる', illust: 'Frog',
      photo: ['Red-eyed Leaf Frog (49661076226).jpg', 'CC BY 2.0', 'Charlie Jackson'],
      tips: ['かえるはごはんをのみこむとき、目玉を口の中にひっこめて、ぐいっとおしこむんだよ。',
        'かえるは皮ふからも呼吸や水分のとりこみをしている。だから乾燥に弱く、きれいな水がある環境の目じるしにもなる。',
        'アメリカアカガエルは、冬に体の一部がこおっても、春にとけると生きかえる。体の中の糖が細胞を守っている。'] },
    { id: 'fish', tier: 1, emoji: '🐟', name: 'さかな', illust: 'Fish',
      photo: ['Balantiocheilos melanopterus - Karlsruhe Zoo 02 (cropped).jpg', 'CC BY-SA 3.0', 'H. Zell'],
      tips: ['魚のうろこには、木の年輪みたいなもようがあって、年れいがわかることがあるんだって。',
        '魚の体の横には「側線（そくせん）」という感覚器があり、水の流れや振動を感じて、群れで泳いだり敵をよけたりする。',
        'マグロのように泳ぎつづけないと呼吸できない魚もいる。口を開けて泳ぎ、えらに水を通す「ラム換水」という方法。'] },
    { id: 'sakura', tier: 1, emoji: '🌸', name: 'さくら', illust: 'Cherry blossom',
      photo: ['Sakura and Moss Pink - 桜(さくら)と芝桜(しばざくら).jpg', 'CC BY 2.0', 'TANAKA Juuyoh (田中十洋)'],
      tips: ['さくらんぼは、さくらの木の実。でもお花見のさくらの実は、すっぱくてあんまりおいしくないよ。',
        'お花見で多い「ソメイヨシノ」は江戸時代の終わりに生まれた品種で、どれも接ぎ木でふやしたクローン。だから同じ地域でいっせいに咲く。',
        '開花予想には「600度の法則」という目安がある。2月1日からの毎日の最高気温を足して600度をこえると咲くころ。'] },
    { id: 'strawberry', tier: 1, emoji: '🍓', name: 'いちご', illust: 'Strawberry',
      photo: ['Garden strawberry (Fragaria × ananassa) single2.jpg', 'CC BY-SA 4.0', 'Ivar Leidus'],
      tips: ['いちごのつぶつぶ、じつはあれが本当の「実」。赤いところは実をのせているお皿なんだって。',
        'いちごはバラ科の植物。りんご・もも・さくらんぼも、同じバラ科のなかま。',
        '赤いところは「花托（かたく）」が大きくなった「偽果（ぎか）」。表面のつぶ1つ1つが「痩果（そうか）」という本当の果実。'] },
    { id: 'penguin', tier: 1, emoji: '🐧', name: 'ペンギン', illust: 'Penguin',
      photo: ['South Shetland-2016-Deception Island–Chinstrap penguin (Pygoscelis antarctica) 04.jpg', 'CC BY-SA 4.0', 'Godot13'],
      tips: ['ペンギンのひざは体の中にかくれている。じつはいつも「空気いす」みたいなかっこうなんだよ。',
        'ペンギンは南半球の鳥。赤道近くのガラパゴス諸島にすむガラパゴスペンギンもいる。',
        'コウテイペンギンは南極の真冬に卵を産み、オスが約2か月、なにも食べずに足の上で卵をあたため続ける。'] },
    { id: 'elephant', tier: 1, emoji: '🐘', name: 'ゾウ', illust: 'Elephant',
      photo: ['178 Male African bush elephant in Etosha National Park Photo by Giles Laurent.jpg', 'CC BY-SA 4.0', 'Giles Laurent'],
      tips: ['ゾウの鼻には骨がない。そのかわり、たくさんの筋肉で水をすってシャワーできるんだ。',
        'ゾウは足の裏で地面の振動を感じとり、遠くの仲間の低い声（超低周波）を聞いていると考えられている。',
        'ゾウはがんになりにくい。がんをふせぐ遺伝子「TP53」を約20組も持っていることが理由のひとつとされる。'] },
    { id: 'giraffe', tier: 1, emoji: '🦒', name: 'キリン', illust: 'Giraffe',
      photo: ['Three giraffes 01.jpg', 'CC BY-SA 4.0', 'Byrdyak'],
      tips: ['あんなに長いキリンの首の骨、数えるとたった7こ。じつは人間と同じ数なんだよ！',
        'キリンの舌は約45cm。とげのある木の葉もからめとって食べる。舌が黒っぽいのは日やけをふせぐため、という説がある。',
        'キリンの血圧は人の約2倍。高いところにある脳まで血を送るためで、足の皮ふがかたくしまって血がたまらない工夫もある。'] },
    { id: 'panda', tier: 1, emoji: '🐼', name: 'パンダ', illust: 'Panda',
      photo: ['Grosser Panda.JPG', 'CC BY-SA 3.0', 'J. Patrick Fischer'],
      tips: ['パンダの手には「6本目のゆび」みたいなでっぱりがあって、竹をしっかりにぎれるんだ。',
        'パンダはクマのなかまで、体のつくりはもともと肉食動物。竹の消化は得意ではなく、1日に十数時間も食べつづける。',
        'パンダは「うま味」を感じる受容体の遺伝子（T1R1）がはたらかなくなっている。肉をおいしく感じにくくなったことが、竹を食べるようになったことと関係すると考えられている。'] },
    { id: 'koala', tier: 1, emoji: '🐨', name: 'コアラ', illust: 'Koala',
      photo: ['Koala climbing tree.jpg', 'CC BY-SA 3.0', 'Diliff'],
      tips: ['コアラは1日に20時間くらいねる。ユーカリの葉っぱはエネルギーが少ないから、省エネモードなんだ。',
        'コアラが食べるユーカリの葉には毒がある。腸の中の細菌の助けで分解して食べている。',
        'コアラの赤ちゃんは、お母さんが出す「パップ」という特別なふんを食べて、ユーカリを分解する腸内細菌を受けつぐ。'] },
    { id: 'rabbit', tier: 1, emoji: '🐰', name: 'うさぎ', illust: 'Rabbit face',
      photo: ['Oryctolagus cuniculus Rcdo.jpg', 'CC BY 3.0', 'JM Ligero Loarte'],
      tips: ['うさぎはうれしいと、ジャンプしながら体をひねる。この「うれしいダンス」はビンキーっていうよ。',
        'うさぎの歯は一生のびつづける。かたい草をたくさん食べて、すりへらしている。',
        'うさぎは自分のやわらかいふん（盲腸便）を食べて、腸の中で作られたビタミンや栄養をもう一度とりこんでいる。'] },
    { id: 'turtle', tier: 1, emoji: '🐢', name: 'カメ', illust: 'Turtle',
      photo: ['Chelonia mydas is going for the air edit.jpg', 'CC BY-SA 3.0', 'Brocken Inaglory'],
      tips: ['カメはこうらをぬげない。こうらは背骨とくっついている、からだの一部なんだ。',
        'ウミガメは自分が生まれた砂浜にもどって卵を産むことが多い。地球の磁場を手がかりにしていると考えられている。',
        'ウミガメの多くは、卵が育つ砂の温度でオスかメスかが決まる。あたたかいとメスが多くなる。'] },
    { id: 'snail', tier: 1, emoji: '🐌', name: 'カタツムリ', illust: 'Snail',
      photo: ['Snail.jpg', 'CC BY-SA 3.0', 'Geierunited'],
      tips: ['カタツムリの口には、小さな歯がなんと1万本以上あるといわれているよ。歯みがきがたいへんそう！',
        'カタツムリのからは体の一部で、からがなくなると生きられない。からのないナメクジは、べつの進化をしたなかま。',
        'カタツムリは「雌雄同体」で、1ぴきがオスとメスの両方の役わりを持つ。2ひきが出会えば、どちらも卵を産める。'] },
    { id: 'honeybee', tier: 1, emoji: '🐝', name: 'ミツバチ', illust: 'Honeybee',
      photo: ['Apis mellifera Western honey bee.jpg', 'CC BY-SA 2.5', 'Andreas Trepte'],
      tips: ['ミツバチ1ぴきが一生で集めるはちみつは、小さじの12分の1くらい。はちみつはみんなの努力のけっしょうなんだ。',
        'ミツバチは「8の字ダンス」で、花のある方向ときょりを仲間に伝える。',
        'ダンスのまっすぐな部分の角度が「太陽の方向とのずれ」、おしりをふる時間の長さが「きょり」をあらわす。この研究でカール・フォン・フリッシュはノーベル賞を受けた。'] },
    { id: 'ladybug', tier: 1, emoji: '🐞', name: 'テントウムシ', illust: 'Lady beetle',
      photo: ['7-Spotted-Ladybug-Coccinella-septempunctata-sq1.jpg', 'CC BY-SA 3.0', 'Dominik Stodulski'],
      tips: ['テントウムシはつかまると、あしから黄色いにがい汁を出して「まずいぞ！」とアピールするんだ。',
        'テントウムシの多くはアブラムシを食べる。畑の害虫を食べてくれる「益虫」として、農薬のかわりに使われることもある。',
        '赤と黒の目立つ色は、鳥に「まずいぞ」と知らせる「警告色」。黄色い汁にはアルカロイドという苦い物質がふくまれる。'] },
    { id: 'butterfly', tier: 1, emoji: '🦋', name: 'チョウ', illust: 'Butterfly',
      photo: ['Fesoj - Papilio machaon (by).jpg', 'CC BY 2.0', 'fesoj'],
      tips: ['チョウは足で味がわかる。花にとまったしゅんかんに「あまい！」ってわかるんだよ。',
        'チョウのはねの色は、鱗粉（りんぷん）という細かいうろこでできている。さわると粉のようにとれるのはそのため。',
        'モルフォチョウの青は色素ではなく、鱗粉の細かいつくりが光を干渉させて見える「構造色」。見る角度で色が変わる。'] },
    { id: 'ant', tier: 1, emoji: '🐜', name: 'アリ', illust: 'Ant',
      photo: ['Red Ant - March 2025.jpg', 'CC BY 2.0', 'Samantha Henneke'],
      tips: ['アリは自分の体重の何十倍もの重さを運べる。人間なら車を持ち上げるくらいの力もちだね。',
        'アリはにおいの道しるべ（フェロモン）をつけて歩き、仲間をえさのある場所へ案内する。',
        'ハキリアリは葉を切って巣に運び、その葉できのこ（菌）を育てて食べる。人間より何千万年も前から「農業」をしている。'] },
    { id: 'donut', tier: 1, emoji: '🍩', name: 'ドーナツ', illust: 'Doughnut',
      photo: ['Glazed-Donut.jpg', 'Public domain', 'Evan-Amos'],
      tips: ['ドーナツのあなは、まん中までしっかり火を通すための工夫だといわれているよ。',
        'ドーナツのあなは、19世紀にアメリカの船長ハンソン・グレゴリーが考えた、という話が有名（本当かどうかは諸説あり）。',
        'あながあると表面積がふえ、生地のどこからでも熱が近くなる。中までむらなく火が通り、揚げる時間も短くできる。'] },
    { id: 'pizza', tier: 1, emoji: '🍕', name: 'ピザ', illust: 'Pizza',
      photo: ['Neapolitan pizza at Trappica (48701940197).jpg', 'CC BY 2.0', 'Bex Walton'],
      tips: ['ピザの「マルゲリータ」は、イタリアの王妃マルゲリータさまの名前からついたといわれているよ。',
        'マルゲリータのトマトの赤・モッツァレラの白・バジルの緑は、イタリア国旗の3色といわれている。',
        'ナポリピッツァは「真のナポリピッツァ協会」が作り方を決めている。薪の窯で約430〜480度、60〜90秒で焼くのが基準。'] },
    { id: 'softcream', tier: 1, emoji: '🍦', name: 'ソフトクリーム', illust: 'Soft ice cream',
      photo: ['Soft Ice cream.jpg', 'Public domain', 'Acidburn24m'],
      tips: ['「ソフトクリーム」は日本で生まれた言い方。英語では「ソフトサーブ」ということが多いんだ。',
        'ソフトクリームは、ふつうのアイスより温度が高め（約−6度前後）で出すので、やわらかく、甘さや香りを感じやすい。',
        'アイスにふくまれる空気の量を「オーバーラン」という。空気が多いほど、ふわっと軽い口あたりになる。'] },
    { id: 'chocolate', tier: 1, emoji: '🍫', name: 'チョコレート', illust: 'Chocolate bar',
      photo: ["Green and Black's dark chocolate bar 2.jpg", 'CC0', 'Mx. Granger'],
      tips: ['チョコのもとのカカオ豆は、むかしのメキシコあたりではお金として使われていたんだって。',
        'カカオにふくまれる「テオブロミン」は、犬やねこには毒になる。ペットにチョコをあげてはいけない。',
        'カカオの学名テオブロマは「神さまの食べ物」という意味。チョコをなめらかにする「テンパリング」は、油の結晶の形をそろえる作業。'] },
    { id: 'egg', tier: 1, emoji: '🥚', name: 'たまご', illust: 'Egg',
      photo: ['Huevo frito.jpg', 'CC BY-SA 4.0', 'Horacio Cambeiro'],
      tips: ['たまごのからには目に見えない小さなあなが何千こもあって、中のひよこはそこから息をしているよ。',
        '白い卵と茶色い卵の栄養はほとんど同じ。からの色はニワトリの品種で決まる。',
        '生卵はまわりにくく、ゆで卵はよくまわる。中身が液体だとブレーキがかかるから。回して指で止めてすぐはなすと、生卵はまた少し動き出す。'] },
    { id: 'bread', tier: 1, emoji: '🍞', name: 'パン', illust: 'Bread',
      photo: ['Korb mit Brötchen.JPG', 'CC BY-SA 3.0', '3268zauber'],
      tips: ['食パンを「1斤（きん）、2斤」と数えるのは、むかしの重さの単位のなごりなんだって。',
        'パンがふくらむのは、酵母（イースト）が糖を食べて二酸化炭素を出すから。',
        '小麦のたんぱく質が作る「グルテン」のあみがガスを閉じこめる。焼くと表面で「メイラード反応」が起き、こんがりした色と香りができる。'] },
    { id: 'watermelon', tier: 1, emoji: '🍉', name: 'スイカ', illust: 'Watermelon',
      photo: ['Taiwan 2009 Tainan City Organic Farm Watermelon FRD 7962.jpg', 'CC BY-SA 3.0', 'Fred Hsu'],
      tips: ['スイカは90%以上が水。食べられる水とうみたいなものだね。',
        'スイカはウリ科で、キュウリやメロンのなかま。ふるさとはアフリカといわれる。',
        '日本の「四角いスイカ」は、箱に入れて育てて形を整えたもの。主にかざる用で、熟す前にとることが多い。'] },
    { id: 'corn', tier: 1, emoji: '🌽', name: 'とうもろこし', illust: 'Ear of corn',
      photo: ['Zea mays - Köhler–s Medizinal-Pflanzen-283.jpg', 'Public domain', 'Franz Eugen Köhler'],
      tips: ['とうもろこしのつぶの数は、たいてい偶数。ひげの数とつぶの数はだいたい同じなんだって。',
        'ポップコーンは、つぶの中の水分が熱で水蒸気になり、皮をやぶって一気にふくらんだもの。',
        'とうもろこしは数千年前のメキシコで、「テオシント」という雑草のような植物から人が品種改良して作ったと考えられている。'] },
    { id: 'carrot', tier: 1, emoji: '🥕', name: 'にんじん', illust: 'Carrot',
      photo: ['Vegetable-Carrot-Bundle-wStalks.jpg', 'Public domain', 'Evan-Amos'],
      tips: ['にんじんを毎日たくさん食べると、手のひらが少し黄色くなることがあるよ（食べる量をへらすともどるよ）。',
        'むかしのにんじんは紫や黄色が多かった。いまのオレンジ色は、17世紀ごろのオランダで広まったといわれる。',
        'オレンジ色のもとは「βカロテン」。体の中でビタミンAに変わり、目や皮ふの健康を守る。'] },
    { id: 'mushroom', tier: 1, emoji: '🍄', name: 'きのこ', illust: 'Mushroom',
      photo: ['Amanita muscaria Aberystwyth 2023.jpg', 'CC BY 4.0', 'Kieran Roy Powell'],
      tips: ['きのこは植物じゃなくて「菌（きん）」のなかま。カビのしんせきなんだよ。',
        '世界でいちばん大きな生き物のひとつは、アメリカの森の地下に広がる「ナラタケ」のなかま。広さは東京ドーム約200こ分。',
        '森の木の根ときのこの菌糸はつながっていて（菌根）、栄養などをやりとりしている。この地下のネットワークは「ウッド・ワイド・ウェブ」とも呼ばれる。'] },
    { id: 'sunflower', tier: 1, emoji: '🌻', name: 'ひまわり', illust: 'Sunflower',
      photo: ['Sunflower head 2026 G1.jpg', 'CC BY 4.0', 'George Chernilevsky'],
      tips: ['ひまわりの種は、うずまきもようにならんでいる。数えると算数のひみつの数がかくれているんだって。',
        'ひまわりは若いつぼみのころ、太陽を追って向きを変える。花が咲くと、多くは東を向いたまま止まる。',
        '種のならびには「フィボナッチ数列」（1, 1, 2, 3, 5, 8, 13…）があらわれ、らせんの数が34と55などになる。'] },
    { id: 'rainbow', tier: 1, emoji: '🌈', name: 'にじ', illust: 'Rainbow',
      photo: ['Double-alaskan-rainbow.jpg', 'CC BY-SA 2.5', 'Eric Rolph'],
      tips: ['にじは本当はまるい形。地面があるから半分しか見えないんだ。飛行機からは丸いにじが見えることも！',
        'にじは、太陽の光が雨つぶの中で曲がり（屈折）、色ごとに分かれて見える。太陽を背にしたときに見える。',
        '外側にうすく見える「副虹（ふくにじ）」は、雨つぶの中で光が2回反射したもの。色のならびが逆で、2本の間の空は暗く見える（アレキサンダーの暗帯）。'] },
    { id: 'cloud', tier: 1, emoji: '☁️', name: 'くも', illust: 'Cloud',
      photo: ['GoldenMedows.jpg', 'CC BY-SA 3.0', 'PiccoloNamek'],
      tips: ['ふわふわの雲も、大きなものはゾウ100頭ぶんくらいの重さがあるんだって。それでもうかんでいるなんてふしぎ！',
        '雲は小さな水や氷のつぶの集まり。とても小さいので、上むきの空気の流れでうかんでいられる。',
        'かみなり雲（積乱雲）は高さ10kmをこえることもある。中の氷のつぶがぶつかり合って電気がたまり、かみなりになる。'] },
    { id: 'sun', tier: 1, emoji: '☀️', name: 'たいよう', illust: 'Sun',
      photo: ['The Sun in white light.jpg', 'CC BY-SA 4.0', 'Matúš Motlo'],
      tips: ['太陽の光が地球にとどくまで、やく8分。いま見ている太陽は、8分前の太陽なんだよ。',
        '太陽の中心の温度は約1500万度。水素がくっついてヘリウムになる「核融合」で、光と熱を出している。',
        '太陽の中心で生まれた光のエネルギーが表面に出てくるまで、数万年から十数万年かかると考えられている。'] },
    { id: 'moon', tier: 1, emoji: '🌙', name: 'つき', illust: 'Crescent moon',
      photo: ['FullMoon2010.jpg', 'CC BY-SA 3.0', 'Gregory H. Revera'],
      tips: ['月はいつも同じ面を地球にむけている。月のうらがわは、地球からはぜったいに見えないんだ。',
        '月は毎年約3.8cmずつ地球から遠ざかっている。アポロが月に置いた鏡にレーザーを当てて測っている。',
        'いつも同じ面を向けるのは「潮汐（ちょうせき）ロック」のため。月が1回自転する時間と、地球のまわりを1周する時間が、どちらも約27.3日で同じ。'] },
    { id: 'snowman', tier: 1, emoji: '⛄', name: 'ゆきだるま', illust: 'Snowman without snow',
      photo: ['Snowman in Indiana 2014.jpg', 'CC BY-SA 3.0', 'GutMaze'],
      tips: ['日本の雪だるまは2だんが多いけど、外国では3だんのものが多いんだって。',
        '雪だるまが作りやすいのは、少しとけかけた水分の多い雪。さらさらの粉雪はかたまりにくい。',
        '雪がぎゅっとかたまるのは、おされたところの氷が少しとけて、またこおる「復氷（ふくひょう）」などのはたらきによる。'] },
    { id: 'balloon', tier: 1, emoji: '🎈', name: 'ふうせん', illust: 'Balloon',
      photo: ['InflatableBalloons.jpg', 'Public domain', 'Complete fanatic'],
      tips: ['ゴムふうせんのもと「天然ゴム」は、ゴムの木から出る白いしる（樹液）からできているよ。',
        'ヘリウムふうせんがうくのは、ヘリウムが空気より軽いから。ヘリウムは地球ではとても貴重な資源。',
        'ふうせんがしぼむのは、ゴムの小さなすき間から気体がもれるから。ヘリウムはつぶがとても小さいので、空気より早くもれる。'] },
    { id: 'socks', tier: 1, emoji: '🧦', name: 'くつした', illust: 'Socks',
      photo: ['HandKnittedWhiteLaceSock.jpg', 'Public domain', 'Loggie-log'],
      tips: ['洗たくするとくつしたの片方だけきえる事件は、世界中で起きているミステリー。くつした星に帰っているのかも？',
        '足の裏には汗を出す汗腺がたくさんあり、1日にコップ1杯くらいの汗をかくといわれる。くつしたはそれを吸いとる役目。',
        '足のにおいの主な原因は、汗をえさにする細菌が作る「イソ吉草酸（きっそうさん）」という物質。'] },
    { id: 'toothbrush', tier: 1, emoji: '🪥', name: 'はブラシ', illust: 'Toothbrush',
      photo: ['Toothbrush 20050716 004.jpg', 'Public domain', 'Jonas Bergsten'],
      tips: ['むかしの人は、木のえだの先をかんでブラシみたいにして、歯をみがいていたんだよ。',
        'いまのようなナイロンの毛の歯ブラシは、1938年にアメリカで発売された。それまでは豚の毛などが使われていた。',
        '毛先が開いた歯ブラシは、よごれを落とす力がぐっと下がる。だいたい1か月での交換がすすめられている。'] },
    { id: 'toiletpaper', tier: 1, emoji: '🧻', name: 'トイレットペーパー', illust: 'Roll of paper',
      photo: ['Toiletpapier (Gobran111).jpg', 'CC BY 2.5', 'Brandon Blinkenberg'],
      tips: ['トイレットペーパーは、水の中でほぐれやすく作られている。だからトイレに流しても大丈夫なんだ。',
        '日本のトイレットペーパーの多くは、牛乳パックなどの古紙をリサイクルして作られている。',
        'ティッシュペーパーは水にとけにくく作られているので、トイレに流すとつまりやすい。紙によって作り方の目的がちがう。'] },
    { id: 'pencil', tier: 1, emoji: '✏️', name: 'えんぴつ', illust: 'Pencil',
      photo: ['Pencils hb.jpg', 'CC BY 3.0', 'Dmgerman'],
      tips: ['えんぴつ1本で線をかきつづけると、50kmくらいかけるといわれているよ。となりの町まで行けちゃうね。',
        'えんぴつのしんは鉛（なまり）ではなく、黒鉛（こくえん）と粘土をまぜて焼いたもの。',
        '「H」はHard（かたい）、「B」はBlack（黒い）の頭文字。粘土が多いほどかたく、黒鉛が多いほど濃くなる。'] },
    { id: 'rice', tier: 1, emoji: '🍚', name: 'ごはん', illust: 'Cooked rice',
      photo: ['Meshi 001.jpg', 'CC0', 'Ocdp'],
      tips: ['お茶わん1ぱいのごはんは、お米のつぶがやく3000つぶ。1つぶも残さず食べたらえらい！',
        '日本では2000年以上前からお米を作っている。稲作は縄文時代の終わりごろ、大陸から伝わったと考えられている。',
        'ご飯をたくと、でんぷんが水と熱でやわらかくなる「糊化（こか）」が起きる。冷めてまたかたくなるのが「老化」。'] },
    // ---------- レア★2 ----------
    { id: 'owl', tier: 2, emoji: '🦉', name: 'フクロウ', illust: 'Owl',
      photo: ['Bubo bubo sibiricus - 01.JPG', 'CC BY-SA 4.0', 'Carlos Delgado'],
      tips: ['フクロウは首を270度もまわせる。うしろを見るのもへっちゃらなんだ。',
        'フクロウの羽のふちはギザギザで、空気の音を小さくする。だから音を立てずに飛べる。新幹線のパンタグラフの騒音対策のヒントにもなった。',
        '左右の耳の高さがずれていて、音がとどく時間の差から、暗やみでもえものの場所を正確につきとめる。'] },
    { id: 'octopus', tier: 2, emoji: '🐙', name: 'タコ', illust: 'Octopus',
      photo: ['Octopus2.jpg', 'CC BY-SA 3.0', 'albert kok'],
      tips: ['タコには心臓が3つもある！しかも血は青い色をしているんだよ。',
        'タコの神経の多くは腕にあり、腕1本1本が自分で考えるように動けるといわれる。',
        '血が青いのは、酸素を運ぶのに銅をふくむ「ヘモシアニン」を使っているから。人の血は鉄をふくむヘモグロビンで赤い。'] },
    { id: 'squid', tier: 2, emoji: '🦑', name: 'イカ', illust: 'Squid',
      photo: ['Sepioteuthis sepioidea (Caribbean Reef Squid).jpg', 'CC BY-SA 3.0', 'Nick Hobgood'],
      tips: ['イカはスミのかたまりを「にせものの自分」にして、てきをだましてにげることがあるんだ。',
        'ダイオウイカの目はバスケットボールくらいの大きさがあるといわれる。暗い深海で、わずかな光をとらえるため。',
        '生きたダイオウイカの姿は長いあいだなぞだったが、2004年に日本の研究チームが深海で初めて撮影に成功した。'] },
    { id: 'shark', tier: 2, emoji: '🦈', name: 'サメ', illust: 'Shark',
      photo: ['White shark.jpg', 'CC BY 2.5', 'Terry Goss'],
      tips: ['サメの歯は、ぬけても何度でも生えかわる。一生で何千本も使うんだって。',
        'サメには硬い骨がなく、体はやわらかい「軟骨」でできている。',
        'サメの皮ふは、歯と同じつくりの小さなうろこ（皮歯）でおおわれ、水の抵抗をへらす。これをまねた競泳水着も作られた。'] },
    { id: 'dolphin', tier: 2, emoji: '🐬', name: 'イルカ', illust: 'Dolphin',
      photo: ['Tursiops truncatus 01-cropped.jpg', 'Public domain', 'NASA'],
      tips: ['イルカはねるとき、脳を半分ずつねむらせる。泳ぎながらねられるんだ。',
        'イルカは「エコーロケーション」といって、音を出し、はね返ってくる音でまわりのようすやえものを知る。',
        'バンドウイルカは1頭ずつ、自分の「名前」のような口笛（シグネチャーホイッスル）を持ち、仲間を呼ぶのに使うと考えられている。'] },
    { id: 'whale', tier: 2, emoji: '🐳', name: 'クジラ', illust: 'Spouting whale',
      photo: ['Humpback whale breaching off Cabo San Lucas.jpg', 'CC BY 4.0', 'Juan Cruzado Cortés'],
      tips: ['シロナガスクジラは地球の歴史でいちばん大きな動物。恐竜よりも大きいんだよ。',
        'クジラは魚ではなく哺乳類。肺で息をし、赤ちゃんにお乳をあげて育てる。',
        'ザトウクジラのオスは何十分もつづく「歌」を歌う。同じ海の仲間は同じ歌を歌い、年ごとに少しずつ変わっていく。'] },
    { id: 'flamingo', tier: 2, emoji: '🦩', name: 'フラミンゴ', illust: 'Flamingo',
      photo: ['010 Greater flamingos male and female in the Camargue during mating season Photo by Giles Laurent.jpg', 'CC BY-SA 4.0', 'Giles Laurent'],
      tips: ['フラミンゴがピンクなのは、食べているエサの色のおかげ。ひなのころは灰色なんだ。',
        'フラミンゴが片足で立つのは、体温をにがさないため、という説が有力。片足のほうが楽に立てるという研究もある。',
        '頭をさかさまにして、くちばしで水をこし、小さなエビや藻を食べる。ピンク色はそのエサにふくまれる「カロテノイド」という色素から。'] },
    { id: 'sloth', tier: 2, emoji: '🦥', name: 'ナマケモノ', illust: 'Sloth',
      photo: ['Bicho-preguiça 3.jpg', 'CC BY-SA 4.0', 'Daniella Maraschiello'],
      tips: ['ナマケモノはのんびりすぎて、毛にコケ（藻）が生えることもあるんだって。',
        'ナマケモノは1週間に1回くらいしか木から降りない。降りるのは、地面でふんをするため。',
        '体のはたらき（代謝）がとてもゆっくりで、食べた葉を消化するのに数日から1か月近くかかるといわれる。'] },
    { id: 'hedgehog', tier: 2, emoji: '🦔', name: 'ハリネズミ', illust: 'Hedgehog',
      photo: ['Erinaceus europaeus LC0119.jpg', 'CC BY-SA 2.0 de', 'Jörg Hempel'],
      tips: ['ハリネズミの針は5000本くらい。こわいときは丸まって、トゲトゲボールに変身！',
        '名前に「ネズミ」とつくが、ネズミのなかまではなく、モグラに近いなかま。',
        '知らないにおいのものをかむと、つばをあわ立てて自分の針にぬりつける「アンティング」をする。理由はまだよくわかっていない。'] },
    { id: 'otter', tier: 2, emoji: '🦦', name: 'ラッコ', illust: 'Otter',
      photo: ['Sea Otter (Enhydra lutris) (25169790524) crop.jpg', 'CC BY-SA 2.0', 'Marshal Hedin'],
      tips: ['ラッコはねるとき、流されないように仲間と手をつなぐことがあるんだって。',
        'ラッコは石を使って貝をわる。お気に入りの石を、わきの下のポケットのようなたるみにしまっておく。',
        'ラッコには皮下脂肪がほとんどなく、1平方センチに10万本以上ともいわれる、ぎっしりの毛に空気をためて体温を保つ。'] },
    { id: 'camel', tier: 2, emoji: '🐫', name: 'ラクダ', illust: 'Two-hump camel',
      photo: ['Camelus bactrianus (55026866188).jpg', 'CC BY-SA 4.0', 'Christian Ursilva'],
      tips: ['ラクダのコブの中身は水じゃなくて「あぶら」。えいようのお弁当箱なんだ。',
        'ラクダは一度に100リットル以上の水を飲めることがある。',
        'ラクダの赤血球はだ円形で、急にたくさん水を飲んでもやぶれにくい。体温を上下させて、汗をへらす工夫もある。'] },
    { id: 'kangaroo', tier: 2, emoji: '🦘', name: 'カンガルー', illust: 'Kangaroo',
      photo: ['Kangaroo Island Western grey kangaroo (Macropus fuliginosus fuliginosus) male.jpg', 'CC BY-SA 4.0', 'Charles J. Sharp'],
      tips: ['カンガルーの赤ちゃんは、生まれたとき1円玉くらいの重さしかないんだよ。',
        'カンガルーは後ろあしと太いしっぽではね、時速50km以上で走ることもある。後ろには歩けないといわれる。',
        'お母さんは、袋の中の赤ちゃん用と、外に出た子ども用で、成分のちがう2種類のお乳を同時に出せる。'] },
    { id: 'crocodile', tier: 2, emoji: '🐊', name: 'ワニ', illust: 'Crocodile',
      photo: ["SaltwaterCrocodile('Maximo').jpg", 'Public domain', 'St. Augustine Alligator Farm'],
      tips: ['ワニは舌を前に出せない。あっかんべーができないんだ。',
        'クロコダイルとアリゲーターは、口を閉じたときの歯でわかる。クロコダイルは下の歯が外から見える。',
        '鳥とワニは、いま生きている動物の中で恐竜にいちばん近い親戚。ワニの祖先は恐竜の時代から生きている。'] },
    { id: 'parrot', tier: 2, emoji: '🦜', name: 'オウム', illust: 'Parrot',
      photo: ['Scarlet macaw (Ara macao cyanopterus) Copan.jpg', 'CC BY-SA 4.0', 'Charles J. Sharp'],
      tips: ['オウムの中には、人の言葉を100以上もおぼえたものがいるんだって。',
        'オウムやインコは足の指が前2本・後ろ2本。足を手のように使って食べ物をつかむ。',
        'ヨウムの「アレックス」は、色や形、数を言葉で答えられたことで有名。オウムのなかまはとても頭がいい。'] },
    { id: 'rooster', tier: 2, emoji: '🐓', name: 'ニワトリ', illust: 'Rooster',
      photo: ['Male and female chicken sitting together.jpg', 'CC BY-SA 2.0', 'Andrei Niemimäki'],
      tips: ['鳥のごせんぞは恐竜のなかま。ニワトリも、ちょっとだけ恐竜なんだよ。',
        'ニワトリはほぼ毎日卵を産めるように品種改良された鳥。祖先の野鳥セキショクヤケイは、年に数回、数こずつしか産まない。',
        'ティラノサウルスの化石から見つかったたんぱく質（コラーゲン）は、ニワトリのものによく似ていた、という研究がある。'] },
    { id: 'duck', tier: 2, emoji: '🦆', name: 'アヒル', illust: 'Duck',
      photo: ['Anas platyrhynchos male female quadrat.jpg', 'CC BY-SA 2.5', 'Richard Bartz'],
      tips: ['アヒルの足は冷たい水でもへっちゃら。足の血のめぐりに、あたたかさをにがさない工夫があるんだ。',
        'アヒルはマガモを家畜にした鳥。羽に油をぬって水をはじくので、水にもぐっても体がぬれない。',
        '足には「対向流熱交換」のしくみがある。あたたかい血と冷たい血がすれちがって熱をもどすので、冷たい水でも体温が下がりにくい。'] },
    { id: 'squirrel', tier: 2, emoji: '🐿️', name: 'リス', illust: 'Chipmunk',
      photo: ['Squirrel posing.jpg', 'CC BY 2.0', 'Peter Trimming'],
      tips: ['リスはどんぐりを土にうめてかくすけど、場所をわすれることも。それが森の木を育てているんだって。',
        'リスの前歯は一生のびつづける。かたい木の実をかじって、すりへらしている。',
        'ムササビやモモンガもリスのなかま。体の横の膜を広げて、100m以上も滑空することがある。'] },
    { id: 'bat', tier: 2, emoji: '🦇', name: 'コウモリ', illust: 'Bat',
      photo: ['Big-eared-townsend-fledermaus.jpg', 'Public domain', 'PD-USGov'],
      tips: ['コウモリは、空をとべるただ1つの哺乳類（ほにゅうるい）。さかさまにぶら下がってねるよ。',
        'コウモリは超音波を出し、そのはね返りで、暗やみでも虫をつかまえる（エコーロケーション）。',
        '哺乳類の種類の約5分の1はコウモリ。チスイコウモリは、血をとれなかった仲間に血を分けてあげる助け合いもする。'] },
    { id: 'snake', tier: 2, emoji: '🐍', name: 'ヘビ', illust: 'Snake',
      photo: ['CornSnake.jpg', 'CC0', 'Ethan Porcaro'],
      tips: ['ヘビにはまぶたがない。だから目をあけたままねむるんだ。',
        'ヘビは舌でにおいを集め、口の上の「ヤコブソン器官」でにおいを感じる。',
        'マムシやガラガラヘビは、目と鼻の間の「ピット器官」で赤外線（熱）を感じ、暗やみでもえものの体温がわかる。'] },
    { id: 'crab', tier: 2, emoji: '🦀', name: 'カニ', illust: 'Crab',
      photo: ['Christmas Island (5774532171).jpg', 'CC BY 2.0', 'DIAC images'],
      tips: ['カニが横歩きなのは、足のつくりが横に動きやすいから。前に歩けるカニもいるんだよ。',
        'カニは脱皮をくりかえして大きくなる。脱皮したばかりのカニは、からがやわらかい。',
        'タラバガニはカニではなくヤドカリのなかま。はさみのほかの歩く足が3対で、カニ（4対）より少ない。'] },
    { id: 'shrimp', tier: 2, emoji: '🦐', name: 'エビ', illust: 'Shrimp',
      photo: ['Palaemon serratus Croazia.jpg', 'Public domain', 'Etrusko25'],
      tips: ['エビの心臓は頭のほうにある。エビフライのしっぽのほうにはないんだ。',
        'エビを加熱すると赤くなるのは、からの「アスタキサンチン」という色素が、たんぱく質からはなれて本来の赤色を出すから。',
        'シャコはエビに似ているがべつのなかま。パンチがとても速く、まわりの水に泡ができるほど。目は人より多くの種類の色を感じるしくみを持つ。'] },
    { id: 'pufferfish', tier: 2, emoji: '🐡', name: 'フグ', illust: 'Blowfish',
      photo: ['Tetraodon-hispidus.jpg', 'Public domain', 'NOAA'],
      tips: ['フグはおこるとお腹に水をすいこんで、ボールみたいにまんまるにふくらむよ。',
        'フグの毒「テトロドトキシン」は青酸カリの約1000倍ともいわれる強い毒。資格を持った人しか料理できない。',
        'フグの毒は自分で作るのではなく、食べたえさにいる細菌がもとと考えられている。毒のないえさで育てた養殖フグは毒を持たないことが多い。'] },
    { id: 'volcano', tier: 2, emoji: '🌋', name: 'かざん', illust: 'Volcano',
      photo: ['Augustine volcano Jan 24 2006 - Cyrus Read.jpg', 'Public domain', 'Cyrus Read (USGS)'],
      tips: ['富士山も火山。いまはねむっているけど、300年くらい前にも噴火したんだよ。',
        '日本には111の活火山がある。世界の活火山の約7%が日本に集まっている。',
        '富士山の最後の噴火は1707年の「宝永噴火」。江戸の町にも火山灰がふりつもった。'] },
    { id: 'cactus', tier: 2, emoji: '🌵', name: 'サボテン', illust: 'Cactus',
      photo: ['Carnegiea gigantea in Saguaro National Park near Tucson, Arizona during November (58).jpg', 'CC BY-SA 3.0', 'WClarke'],
      tips: ['サボテンのトゲは、じつは「葉っぱ」が変身したもの。水をにがさないための作戦なんだ。',
        'サボテンは昼に気孔を閉じ、夜に開いて二酸化炭素をとりこむ。昼の暑さで水をにがさない工夫。',
        'このしくみを「CAM型光合成」という。写真のサワロサボテンは高さ15mをこえ、150年以上生きることもある。'] },
    { id: 'pineapple', tier: 2, emoji: '🍍', name: 'パイナップル', illust: 'Pineapple',
      photo: ['കൈതച്ചക്ക.jpg', 'CC BY 3.0', 'Suniltg'],
      tips: ['パイナップルは1つの実じゃなくて、たくさんの小さな実が合体したものなんだよ。',
        'パイナップルには、たんぱく質を分解する酵素「ブロメライン」がふくまれる。食べると舌がピリピリするのはそのため。',
        '植えてから実がなるまで1年半〜2年かかり、1つの株から実はふつう1こしかならない。'] },
    { id: 'avocado', tier: 2, emoji: '🥑', name: 'アボカド', illust: 'Avocado',
      photo: ['Persea americana fruit 2.JPG', 'CC BY-SA 3.0', 'B.navez'],
      tips: ['アボカドは「森のバター」とよばれるくらい、あぶらがたっぷりの果物なんだ。',
        'アボカドは、木からとったあとに熟す果物。木についたままではやわらかくならない。',
        '大きな種は、絶滅した大型動物（オオナマケモノなど）に丸のみされて運ばれていた、という説がある。'] },
    { id: 'cheese', tier: 2, emoji: '🧀', name: 'チーズ', illust: 'Cheese wedge',
      photo: ['Emmentaler Premier Cru.jpg', 'CC BY-SA 2.0 de', 'Manuel2'],
      tips: ['チーズのあなは、中の小さな生きもの（菌）がガスを出してできるんだって。',
        'チーズは牛乳に「レンネット」という酵素や乳酸菌を加えて、かためて作る。',
        'エメンタールチーズの大きなあなは「プロピオン酸菌」が出す二酸化炭素。小さな干し草のかけらが、あなのきっかけになるという研究もある。'] },
    { id: 'honey', tier: 2, emoji: '🍯', name: 'はちみつ', illust: 'Honey pot',
      photo: ['Runny hunny.jpg', 'Public domain', 'Scott Bauer, USDA ARS'],
      tips: ['はちみつはとてもくさりにくい。何千年も前のはちみつが見つかったこともあるんだよ。',
        'はちみつは1歳未満の赤ちゃんに食べさせてはいけない。ボツリヌス菌の芽胞がふくまれることがあるため。',
        '糖が多く水分が少ない（約20%）ので、細菌は水分をうばわれて増えられない。酵素が作る過酸化水素にも殺菌作用がある。'] },
    { id: 'tornado', tier: 2, emoji: '🌪️', name: 'たつまき', illust: 'Tornado',
      photo: ['F5 tornado Elie Manitoba 2007.jpg', 'CC BY-SA 3.0', 'Justin Hobson'],
      tips: ['たつまきの風は、新幹線より速いこともあるんだって！',
        'たつまきは、かみなり雲の下で起きるはげしいうずまき。日本でも1年に20こほど確認されている。',
        'たつまきの強さは「藤田スケール」であらわす。考えたのは日本出身の気象学者・藤田哲也博士。'] },
    { id: 'snowflake', tier: 2, emoji: '❄️', name: 'ゆきのけっしょう', illust: 'Snowflake',
      photo: ['Snowflake (lumehelves).jpg', 'CC BY 4.0', 'Janek Lass'],
      tips: ['雪のけっしょうはたいてい六角形。まったく同じ形のけっしょうを見つけるのはとてもむずかしいんだ。',
        '雪のけっしょうの形は、空の温度と湿度で決まる。中谷宇吉郎博士は「雪は天から送られた手紙である」という言葉を残した。',
        '中谷博士は1936年、世界で初めて人工雪を作ることに成功した。温度と水蒸気の量で形が変わる図は「中谷ダイヤグラム」と呼ばれる。'] },
    // ---------- レア★3 ----------
    { id: 'unicorn', tier: 3, emoji: '🦄', name: 'ユニコーン', illust: 'Unicorn',
      photo: ['Oftheunicorn.jpg', 'Public domain', 'Conrad Gessner'],
      tips: ['スコットランドでは、ユニコーンが国の動物になっているんだって。本当の話だよ！',
        '中世ヨーロッパでは「ユニコーンの角」として、北の海にすむイッカクというクジラの牙が、とても高い値段で売られていた。',
        'ユニコーンの角には毒を消す力があると信じられ、王さまの杯にも使われた。フランスのタペストリー「貴婦人と一角獣」は中世美術の名作。'] },
    { id: 'dragon', tier: 3, emoji: '🐉', name: 'ドラゴン', illust: 'Dragon',
      photo: ['Azure Dragon.jpg', 'CC BY-SA 4.0', '沃德利成書畫院'],
      tips: ['西洋のドラゴンは火をはき、東洋の竜は雨をふらせる。竜にもお国がらがあるんだね。',
        '中国の竜は「九似（きゅうじ）」といって、9種類の動物に似たところを持つといわれる（角は鹿、うろこは鯉など）。',
        '実在するトカゲ「コモドオオトカゲ」は「コモドドラゴン」とも呼ばれる。世界最大のトカゲで、全長3mになることもある。'] },
    { id: 'mermaid', tier: 3, emoji: '🧜', name: 'にんぎょ',
      illust: { wiki: ['John William Waterhouse A Mermaid.jpg', 'Public domain', 'John William Waterhouse'] },
      photo: ['Dugong.JPG', 'CC BY-SA 3.0 de', 'Gejuni'],
      tips: ['むかしの船乗りが見た「にんぎょ」は、ジュゴンやマナティーだったという説があるんだ。',
        'アンデルセンの「人魚姫」の像はデンマークのコペンハーゲンにある。高さは約1.25mで、意外と小さい。',
        '写真のジュゴンやマナティーは「海牛（かいぎゅう）」のなかまで、じつはゾウに近い親戚。海草を食べるおだやかな動物。'] },
    { id: 'fairy', tier: 3, emoji: '🧚', name: 'ようせい', illust: 'Person fairy/Default/3D/person_fairy_3d_default.png',
      photo: ['Fairy ring on a suburban lawn 100 1851.jpg', 'Public domain', 'Mrs skippy'],
      tips: ['外国には、ぬけた歯をまくらの下におくと、ようせいがコインと交換してくれるという言い伝えがあるよ。',
        '1917年、イギリスの少女たちが「ようせいの写真」をとり、本物だと大さわぎになった（コティングリー妖精事件）。',
        'その写真は1980年代に、本の絵を切りぬいた作り物だったと本人たちが告白した。ホームズの作者コナン・ドイルも本物だと信じていた。写真は、きのこが輪になって生える「妖精の輪（フェアリーリング）」。'] },
    { id: 'genie', tier: 3, emoji: '🧞', name: 'ランプのまじん', illust: 'Person genie/3D/person_genie_3d.png',
      photo: ['Group of ancient hellenistic an roan oil lamps.jpg', 'CC BY-SA 4.0', 'Combirom2'],
      tips: ['ランプのまじんは、アラビアのお話「千夜一夜物語」で有名になったんだよ。3つのねがい、きみなら何にする？',
        '「アラジンと魔法のランプ」は、もともとのアラビア語の写本にはなく、18世紀にフランスで加えられたお話。',
        '「ジン」はアラビアの伝承で、けむりのない火から作られたとされる存在。写真は古代の油のランプ。'] },
    { id: 'ghost', tier: 3, emoji: '👻', name: 'おばけ', illust: 'Ghost',
      photo: ['Hammersmith Ghost.PNG', 'Public domain', 'Colonel Warden'],
      tips: ['「おばけ」は「化ける」から来た言葉。すがたを変えるから「お化け」なんだって。',
        '日本の幽霊に足がない絵は、江戸時代の画家・円山応挙が広めたといわれる。',
        '古い道具が長い年月をへて妖怪になったものを「付喪神（つくもがみ）」という。物を大切にしなさい、という教えでもある。'] },
    { id: 'alien', tier: 3, emoji: '👽', name: 'うちゅうじん', illust: 'Alien',
      photo: ['Roswell Alien Streetlight 4889004723.jpg', 'CC BY 2.0', 'CGP Grey'],
      tips: ['宇宙人からのメッセージをさがす研究は、本当に何十年もつづけられているんだよ。',
        '知的な宇宙人がいる星の数を見積もる式を「ドレイクの方程式」という。写真はアメリカ・ロズウェルの宇宙人の街灯。',
        '1977年、アメリカの電波望遠鏡が宇宙から強い信号をとらえ、記録用紙に「Wow!」と書かれた（Wow!シグナル）。正体はまだわかっていない。'] },
    { id: 'trex', tier: 3, emoji: '🦖', name: 'ティラノサウルス', illust: 'T-rex',
      photo: ['Tyrannosaurus Rex Holotype.jpg', 'CC BY-SA 3.0', 'ScottRobertAnselmo'],
      tips: ['ティラノサウルスの腕は、体のわりにとても短い。頭がかゆくても、かけなかったかも？',
        'ティラノサウルスのかむ力は数トンもあったと考えられている。骨ごとかみくだけるほど。',
        'いちばん有名な化石のひとつ「スー」は全長約12m。羽毛の生えたティラノサウルスのなかまも見つかっている。'] },
    { id: 'plesiosaur', tier: 3, emoji: '🦕', name: 'くびながりゅう', illust: 'Sauropod',
      photo: ['Plesiosaurus dolichodeirus NHM.jpg', 'CC BY 2.0', 'the paleobear'],
      tips: ['海にいた首長竜は、じつは恐竜とはべつのなかま。でも、どっちもかっこいい！',
        '日本でも首長竜の化石が見つかっている。福島県の「フタバスズキリュウ」は高校生が発見した。',
        '首長竜（プレシオサウルスのなかま）は爬虫類だが恐竜ではなく、海の中で赤ちゃんを産んでいたことが化石からわかっている。'] },
    { id: 'mammoth', tier: 3, emoji: '🦣', name: 'マンモス', illust: 'Mammoth',
      photo: ['Siegsdorfer Mammut.jpg', 'Public domain', 'Lou.gruber'],
      tips: ['エジプトでピラミッドが作られていたころ、北の島にはまだマンモスが生きていたんだって。',
        'マンモスはゾウのなかま。寒い土地のケナガマンモスは、長い毛と小さな耳で寒さに強かった。',
        'シベリアの永久凍土からは、肉や毛が残ったマンモスが見つかることがある。北極海のウランゲリ島では約4000年前まで生き残っていた。'] },
    { id: 'peacock', tier: 3, emoji: '🦚', name: 'クジャク', illust: 'Peacock',
      photo: ['Peacock on tree (52077240794).jpg', 'CC BY 2.0', 'Kandukuru Nagarjun'],
      tips: ['クジャクのきれいな羽は、オスだけ。メスに「見て見て！」とアピールするためなんだ。',
        'オスの長い飾り羽は、しっぽではなく、背中の羽（上尾筒＝じょうびとう）がのびたもの。',
        '羽の目玉もようは色素ではなく「構造色」。ダーウィンは、クジャクの羽を見ると気分が悪くなると手紙に書いた（自然選択だけでは説明しにくかったため）。'] },
    { id: 'saturn', tier: 3, emoji: '🪐', name: 'どせい', illust: 'Ringed planet',
      photo: ['Saturn global view from Cassini, rings open Better Colour.png', 'Public domain', 'NASA / JPL-Caltech / SSI'],
      tips: ['土星はとても軽い。土星が入るくらい大きなお風呂があったら、ぷかっとうくといわれているよ。',
        '土星の輪は、主に氷のつぶでできている。小さなつぶから、家くらいの大きさのものまである。',
        '輪の直径は約27万kmもあるのに、厚さは多くの場所で数十mほどしかない。数億年後には消えてしまうかもしれないといわれる。'] },
    { id: 'comet', tier: 3, emoji: '☄️', name: 'ほうきぼし', illust: 'Comet',
      photo: ['Comet Hale-Bopp 1995O1.jpg', 'CC BY-SA 3.0', 'E. Kolmhofer, H. Raab'],
      tips: ['ほうき星（すい星）のしっぽは、いつも太陽と反対がわにのびるんだよ。',
        'すい星は「よごれた雪だるま」とも呼ばれる、氷とちりのかたまり。太陽に近づくととけて、しっぽができる。',
        'ハレーすい星は約76年ごとに地球に近づく。次に見られるのは2061年。'] },
    { id: 'shootingstar', tier: 3, emoji: '🌠', name: 'ながれぼし', illust: 'Shooting star',
      photo: ['Perseid Meteor Shower at Mojave National Preserve (51374983157) (cropped).jpg', 'CC BY 2.0', 'Jim Vajda'],
      tips: ['流れ星は、宇宙のちりが空気とこすれて光っているもの。すなつぶくらいの大きさのものが多いんだ。',
        'ペルセウス座流星群のように、毎年決まった時期にたくさんの流れ星が見られる「流星群」がある。',
        '流星群は、すい星が通ったあとに残したちりの帯の中に、地球が毎年同じ時期に飛びこむことで起こる。'] },
    { id: 'wizard', tier: 3, emoji: '🧙', name: 'まほうつかい', illust: 'Person mage/Default/3D/person_mage_3d_default.png',
      photo: ['The Enchanted Garden of Messer Ansaldo by Marie Spartali Stillman (1889).jpg', 'Public domain', 'Marie Spartali Stillman'],
      tips: ['まほうつかいのぼうしがとんがっている本当の理由は、だれも知らない。きみが考えてもいいんだよ。',
        'とんがりぼうしのまほうつかいのイメージは、むかしの学者や占星術師の服装、絵本のさし絵などがまざって広まったと考えられている。',
        '中世の「錬金術」は、金を作るだけの研究ではなく、蒸留などの技術を通して、いまの化学のもとになった。ニュートンも錬金術を研究していた。'] },
    // ---------- SR ----------
    { id: 'crown', tier: 4, emoji: '👑', name: 'おうかん', illust: 'Crown',
      photo: ['Imperial State Crown.png', 'Public domain', 'Cyril Davenport'],
      tips: ['イギリスの王さまの王冠には、2000こ以上のダイヤモンドがちりばめられているんだって。まぶしい！',
        'びんのふたの「王冠」は、形が王冠に似ていることから名前がついた。英語でも「クラウン・コルク」という。',
        'びんの王冠のギザギザは21こが標準。1892年にアメリカのウィリアム・ペインターが発明した。'] },
    { id: 'diamond', tier: 4, emoji: '💎', name: 'ダイヤモンド', illust: 'Gem stone',
      photo: ['Rough Diamond.jpg', 'CC0', 'DGPC/ADF Luísa Oliveira'],
      tips: ['ダイヤモンドは、えんぴつのしん（黒鉛）と同じ「炭素」からできているんだよ。まるで変身だね！',
        'ダイヤモンドは天然でいちばんかたい鉱物。でもハンマーでたたくとわれることがある（かたいけど、われにくいわけではない）。',
        'ダイヤモンドは地下150km以上の、とても高温・高圧の場所でできる。かたさの目安「モース硬度」は10。写真は原石。'] },
    { id: 'trophy', tier: 4, emoji: '🏆', name: 'トロフィー', illust: 'Trophy',
      photo: ['FIFA World Cup Trophy photo by Djuradj Vujcic.jpg', 'CC BY 2.0', 'Djuradj Vujcic'],
      tips: ['サッカーのワールドカップのトロフィーは、本物の金でできているんだよ。',
        'いまのワールドカップのトロフィーは、優勝国でも持ち帰れない。優勝国には金メッキのレプリカがわたされる。',
        '初代のトロフィー「ジュール・リメ杯」は1983年にブラジルでぬすまれ、いまも見つかっていない。'] },
    { id: 'milkyway', tier: 4, emoji: '🌌', name: 'ぎんが', illust: 'Milky way',
      photo: ['ESO-VLT-Laser-phot-33a-07.jpg', 'CC BY 4.0', 'ESO/Y. Beletsky'],
      tips: ['天の川は、何千億もの星のあつまり。わたしたちの太陽も、その中のひとつなんだ。',
        '天の川銀河には、1000億〜4000億こほどの星があると考えられている。',
        '天の川銀河の中心には、太陽の約400万倍の重さのブラックホール「いて座A*」がある。2022年にその姿が撮影された。'] },
    { id: 'crystalball', tier: 4, emoji: '🔮', name: 'すいしょうだま', illust: 'Crystal ball',
      photo: ['A crystal ball at work.jpg', 'CC BY-SA 4.0', 'PLBechly'],
      tips: ['水晶は時計にも使われている。電気を流すと、とても正確にふるえるんだって。',
        '水晶は二酸化ケイ素の結晶で、ガラスと同じ成分。きれいな六角柱の形に育つ。',
        '水晶は力を加えると電気を生む「圧電効果」を持つ。クオーツ時計は水晶を1秒に32768回ふるわせて時間をはかる。'] },
    { id: 'key', tier: 4, emoji: '🗝️', name: 'ひみつのかぎ', illust: 'Old key',
      photo: ['Solex 99 30 padlock with keys (DSCF2659).jpg', 'CC BY 4.0', 'Trougnouf'],
      tips: ['このかぎで開くとびらは、まだだれも見つけていない…。もしかしたら、きみの家のどこかにあるかも？',
        'いちばん古いかぎのひとつは古代エジプトの木のかぎ。ピンを持ち上げて開けるしくみは、いまのかぎにもつながっている。',
        'いまの多くのかぎ（ピンタンブラー錠）は、長さのちがう小さなピンがそろったときだけ回るしくみ。19世紀にアメリカのイェール親子が改良した。'] },
    { id: 'gift', tier: 4, emoji: '🎁', name: 'まぼろしのプレゼント', illust: 'Wrapped gift',
      photo: ['Traditional Japanese wrapping cloth,huroshiki,katori-city,japan.JPG', 'CC BY 3.0', 'katorisi'],
      tips: ['サンタさんが一晩で世界中にプレゼントをくばるには、ものすごいスピードがいるらしい。さすがサンタさん！',
        'サンタクロースのモデルは、4世紀ごろの聖ニコラウスという人だといわれる。写真は日本のつつみ方「ふろしき」。',
        'アメリカとカナダの防空組織NORADは、毎年クリスマスイブに「サンタ追跡」を公開している。始まりは1955年の広告の電話番号のまちがい。'] },
    { id: 'moneybag', tier: 4, emoji: '💰', name: 'おたからぶくろ', illust: 'Money bag',
      photo: ['Kiloware.JPG', 'CC BY-SA 4.0', 'Michael Sander'],
      tips: ['1円玉は、水にそっとのせるとうくことがあるよ。1まいたった1gしかないからなんだ。',
        '1円玉はアルミニウムでできている。1まい作るのに1円より多くの費用がかかるといわれる。',
        'お札はふつうの紙ではなく、ミツマタなどの植物のせんいを使った特別な紙。すかしやホログラムなど、まねできない工夫がたくさんある。'] },
    { id: 'miraclestar', tier: 4, emoji: '🌟', name: 'きせきのほし', illust: 'Glowing star',
      photo: ['2012-03-14 21-42-55-file-etoiles-14f-2min-3d.jpg', 'CC BY 3.0', 'Thomas Bresson'],
      tips: ['このほしを見つけたきみは、とってもラッキーな幸運のもちぬし！',
        '星が「またたく」のは、地球の空気のゆらぎで光が曲げられるから。宇宙から見ると、星はまたたかない。',
        'いま見ている星の中には、もう爆発してなくなっている星があるかもしれない。光が地球にとどくまでに長い時間がかかるため。'] },
    { id: 'clover', tier: 4, emoji: '🍀', name: 'よつばのクローバー', illust: 'Four leaf clover',
      photo: ['Four-leaf Clover Trifolium repens 2.jpg', 'Public domain', 'KEBman'],
      tips: ['四つ葉のクローバーは、1万本に1本くらいしかないといわれているよ。見つけたらラッキー！',
        'シロツメクサ（クローバー）は、江戸時代にオランダからガラス器を運ぶときのつめもの（クッション）として来たので「詰め草」という名前がついた。',
        '四つ葉ができるのは、遺伝や、成長点がふまれて傷つくことなどが原因と考えられている。人がよく歩く場所で見つかりやすいといわれる。'] }
  ]
};
